# Generated by Django 5.0.6 on 2024-06-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('User', 'User'), ('Moderator', 'Moderator'), ('Premium', 'Premium'), ('Admin', 'Admin')], default='User', max_length=20),
        ),
    ]
