# Generated by Django 5.0.6 on 2024-06-19 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_uploadedfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
